name: Update Resume Gist

on: push

jobs:
  update-resume-gist:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Update Resume Gist
      uses: exuanbo/actions-deploy-gist@v1
      with:
        token: ${{ secrets.GIST_ACCESS_TOKEN }}
        gist_id: 48f0bb19c9bad580f8d094bb8cf12b3d
        gist_description: "resume.json gist for https://registry.jsonresume.org"
        gist_file_name: "resume.json"
        file_path: resume/resume.json
        file_type: text
